---
abstract: 'Clear, readable syntax for command line processing'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Data::Dumper: 0
  Exception::Class::TryCatch: 1.10
  File::Find: 0
  File::Temp: 0
  Test::More: 0.62
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Lucid
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Getopt::Lucid:
    file: lib/Getopt/Lucid.pm
    version: 1.01
  Getopt::Lucid::Exception:
    file: lib/Getopt/Lucid/Exception.pm
    version: 1.01
  Getopt::Lucid::Spec:
    file: lib/Getopt/Lucid.pm
    version: 1.01
requires:
  Carp: 0
  Exception::Class: 1.23
  Exporter: 0
  Storable: 2.16
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Getopt-Lucid
  homepage: https://github.com/dagolden/getopt-lucid
  repository: https://github.com/dagolden/getopt-lucid.git
version: 1.01
